name: Deploy Client to Render

on:
  push:
    branches: [ main ]
    paths:
      - 'client/**'
      - '.github/workflows/deploy-client.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: render/deploy-action@v1
        with:
          service-id: ${{ secrets.RENDER_CLIENT_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }} 